from setuptools import setup, find_packages

setup(
    name='quantization_torch',
    version='0.0.1',
    description='model quantization module for AIS',
    author='swim',
    author_email='swim@surromind.ai',
    url='https://github.com/angseung/quantization_torch',
    install_requires=[
        'matplotlib',
        'numpy',
        'opencv-python',
        'Pillow',
        'PyYAML',
        'requests',
        'scipy',
        'torch',
        'torchvision',
        'tqdm',
        'tensorboard',
        'pandas',
        'seaborn',
        'onnx',
        'ipython',
        'psutil',
        'thop',
        'onnxruntime',
        'timm',
    ],
    packages=find_packages(exclude=[]),
    package_data={'quantization_torch': ['*.py'],
                  'data': ['data/*', 'data/hyps/*.yaml'],
                  'fonts': ['fonts/*'],
                  },
    include_package_data=True,
    keywords=['quantization', 'pypi'],
    python_requires='>=3.9',
    zip_safe=False,
    classifiers=[
        'Programming Language :: Python :: 3.9',
    ],
)
