from setuptools import setup, find_packages

setup(
    name="quantization_torch",
    version="0.0.2",
    description="model quantization module for AIS",
    author="angseung",
    author_email="angseung@vueron.com",
    url="https://github.com/angseung/quantization_torch.git",
    install_requires=[
        "matplotlib",
        "numpy",
        "opencv-python",
        "Pillow<=9.5.0",
        "PyYAML",
        "requests",
        "scipy",
        "torch>=2.0.1",
        "torchvision>=0.15.2",
        "tqdm",
        "tensorboard",
        "pandas",
        "seaborn",
        "onnx",
        "ipython",
        "psutil",
        "thop",
        "onnxruntime",
        "timm",
    ],
    packages=find_packages(exclude=[]),
    package_data={
        "quantization_torch": ["fonts/*", "main/*.py", "data/*", "data/hyps/*.yaml"],
    },
    include_package_data=True,
    keywords=["quantization", "pypi"],
    python_requires=">=3.9",
    zip_safe=False,
    classifiers=[
        "Programming Language :: Python :: 3.9",
    ],
)
